{% set name = "sarsen" %}
{% set version = "0.9.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56bbdb382719b506852a8f63c68f0d9f434fcb4dbe9130b8ac0238b3f8ee2eb1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sarsen = sarsen.__main__:app

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - attrs
    - flox
    - numpy
    - pandas
    - python >={{ python_min }}
    - rasterio
    - rioxarray
    - typer
    - xarray >=2022.06.0
    - xarray-sentinel >=0.9.3

test:
  imports:
    - sarsen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sarsen/
  summary: Algorithms and utilities for Synthetic Aperture Radar (SAR) sensors
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomAugspurger
    - aurghs
    - alexamici
